# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: itunes_ingestion 0.3.0 ruby lib

Gem::Specification.new do |s|
  s.name = "itunes_ingestion"
  s.version = "0.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Francis Chong", "Michael Franken"]
  s.date = "2015-12-10"
  s.description = "A simple port of Apple itunes Autoingestion tool to ruby."
  s.email = "mfranken@zilverline.com"
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "itunes_ingestion.gemspec",
    "lib/itunes_ingestion.rb",
    "lib/itunes_ingestion/company_sales.rb",
    "lib/itunes_ingestion/fetcher.rb",
    "lib/itunes_ingestion/sales_report_parser.rb",
    "spec/fetcher_spec.rb",
    "spec/fixtures/report.txt",
    "spec/sales_report_parser_spec.rb"
  ]
  s.homepage = "http://github.com/zilverline/itunes-auto-ingestion"
  s.rubygems_version = "2.4.5.1"
  s.summary = "A simple port of Apple itunes Autoingestion tool to ruby."
  s.test_files = ["spec/fetcher_spec.rb", "spec/fixtures", "spec/fixtures/report.txt", "spec/sales_report_parser_spec.rb"]

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rest-client>, [">= 0"])
    else
      s.add_dependency(%q<rest-client>, [">= 0"])
    end
  else
    s.add_dependency(%q<rest-client>, [">= 0"])
  end
end

